[tool.poetry]
name = "project-2_lukyanchikov"
version = "0.1.0"
description = "Примитивная консольная БД — учебный проект"
authors = ["Лукьянчиков <you@example.com>"]
packages = [
    { include = "src" },
]

[tool.poetry.dependencies]
python = ">=3.12"
prompt-toolkit = "^3.0.0"
prettytable = "*"


[tool.poetry.group.dev.dependencies]
prettytable = "*"


[tool.poetry.scripts]
project = "src.primitive_db.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = ["venv", ".venv", "dist", "__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []